### ISSUE TITLE
Decoding with multiple threads?

### ISSUE THREAD

**Issue by jd20** [mikeboers/PyAV#303] opened 2018-04-02 06:57 UTC
I was doing some decoding benchmarks with PyAV, and had a question about decoding in multiple threads. I'm trying to decode several mp4 files, each one in it's own thread. However, total CPU usage never exceeds 100%, it's almost as if PyAV has some sort of internal lock that doesn't allow more than one thread to decode at a time.

Does anyone understand why decoding multiple files with PyAV doesn't scale with multiple threads? I've looked through the code, but am not seeing anything super obvious. This is with Python 3.6, CPython on MacOS. The decode loop I'm running in each thread is very simple, basically:

```python
def decode(input_file):
    container = av.open(input_file)
    for _ in container.decode(video=0):
        pass

def main():
    for input_file in sys.argv[1:]:
        t = threading.Thread(target=decode, args=(input_file,))
        t.start()
```

PS: I haven't tried experimenting with PyPy yet, but I wouldn't think CPython's GIL is a problem, since almost all the heavy lifting is being done in ffmpeg libraries, not Python code. Correct me if I'm wrong on this though...

**Comment by sdvillal** [comment] 2018-04-02 09:50
I'm not sure if pyav releases the GIL. In this case, you should probably go instead with multiprocessing (spawning a new worker per video file should be fine unless your videos are small). But wouldn't your best bet be to instruct ffmpeg to take care of multithreading? I have these two lines in an old piece of code (using pyav 1.3.3):

```python
        self._stream = self._container.streams.video[self.video_stream_index]
        self._stream.thread_count = num_threads  
        # next version of pyav will have this moved to CodecContext
```

**Comment by jd20** [comment] 2018-04-02 10:01
Thanks @sdvillal, unfortunately spawning a process per video file isn't an option for me. I didn't realize the GIL has to be explicitly released in C extensions. Would it be pretty straight-forward to fix that, or are there some hidden gotcha's?

I tried setting thread_count too, even though it's not ideal for my situation (I'd rather keep each decoder single-threaded, and parallelize at the file level), however I still didn't see any performance improvement or CPU utilization above 100%. I tried both setting `stream.thread_count` right after `av.open`, and re-creating the codec context after setting `thread_count` on the stream. Neither seemed to have any effect, would be great if we had a canonical example of how to set thread_count somewhere, I couldn't find one.

**Comment by wegel** [comment] 2018-04-09 17:40
Considering this issue, could it be that we need to set https://www.ffmpeg.org/doxygen/3.1/structAVCodecContext.html#a5f4579d94675579e1d46a591340f598f to `FF_THREAD_SLICE|FF_THREAD_FRAME` ? I wasn't able to determine if PyAV tries to set this at this point (not familiar enough with Cython at this point), but I could find any reference to `active_thread_type` or the 2 above enums in the PyAV code. I don't think the libav* libs will do multithreading if `active_thread_type` is left at its default value.

**Comment by mikeboers** [comment] 2018-04-09 19:08
I don't have time to dig into this now, but I'll quickly note that PyAV [does][g1] [release][g2] [the][g3] [gil][g4].

[g1]: https://github.com/mikeboers/PyAV/blob/develop/include/libavformat/avformat.pxd#L4
[g2]: https://github.com/mikeboers/PyAV/blob/develop/include/libavcodec/avcodec.pxd#L4
[g3]: https://github.com/mikeboers/PyAV/blob/develop/include/libavfilter/avfilter.pxd#L2
[g4]: https://github.com/mikeboers/PyAV/blob/develop/include/libavutil/avutil.pxd#L10

**Comment by wegel** [comment] 2018-04-09 19:16
I'll try to take a look once I read up on Cython.

**Comment by mikeboers** [comment] 2018-04-09 19:48
No. It looks reasonable. How are you building the Cython?

In other news, I can confirm that not only will a single container not use multiple threads to decode, but multiple containers don't seem to decode at the same time.

I also had to band-aid over another Cython bug to test it. _grumbles_

**Comment by wegel** [comment] 2018-04-09 19:56
Not sure if this is what you want to know, but I'm "manually" building PyAV by cloning the repo and `make`, basically, in a docker container, using the libav* libs built in a previous step (currently building 3.4.2).

The relevant section of my Dockerfile (not totally clean, but well It works For Me ;)):

```
#dirty hack with sed to insert patch, while testing
RUN	git clone https://github.com/mikeboers/PyAV && \
	cd PyAV && \
	sed -i 's/int thread_count/int thread_count\n        int thread_type/g' include/libavcodec/avcodec.pxd && \
	sed -i '492i\    property thread_type:\n        def __get__(self):\n            return self.ptr.thread_type\n        def __set__(self, int value):\n            self.ptr.thread_type = value'  av/codec/context.pyx && \
	git diff && \
	cat include/libavcodec/avcodec.pxd && \
	cat av/codec/context.pyx  && \
	bash -c "PYAV_LIBRARY_VERSION=3.4 source scripts/activate.sh && \
	pip install Cython && \
	PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/opt/ffmpeg/lib/pkgconfig/ && \
	make && python setup.py bdist_wheel" && \
	pip install ./dist/*.whl
```

I'm installing the wheel file in another container (actually, in another step of a multi-stage Dockerfile).

It's good news to me that you confirm that we're not multithreaded yet, it means we can still get a substantial performance upgrade in the future ;) That plus the eventual `hwaccel` will give quite a nice boost.

**Comment by jd20** [comment] 2018-04-09 20:06
My finding was same as @mikeboers, multiple containers will not decode at the same time. @wegel: I might have some time this month to dig deeper into this, if you need help.

**Comment by wegel** [comment] 2018-04-09 20:41
My bad, of course I was testing with a non-updated container. The above patch works to introduce a  `thread_type` field, but setting it to 3 (which should be equivalent to `FF_THREAD_SLICE|FF_THREAD_FRAME`) doesn't seem to change anything; I get multiple threads, but not sure if I had those previously, and performance seems the same.

I'll investigate more in the next few days.

**Comment by wegel** [comment] 2018-04-10 00:37
Nice, thanks for the tip. I'll go with the attribute on `av.open` if I get there before you have time to, I think.

**Comment by mikeboers** [comment] 2018-04-10 00:51
And something about [this call](https://github.com/mikeboers/PyAV/blob/develop/av/codec/context.pyx#L241) causes it to hold into the GIL. If it is expanded from:

    err_check(lib.avcodec_send_packet(self.ptr, packet_ptr))

 into:

    cdef int rescode
    with nogil:
        rescode = lib.avcodec_send_packet(self.ptr, packet_ptr)
    err_check(rescode)

Then I start actually decoding multiple at once.

I don't understand that. I feel like Cython isn't handling it right. Anyone (dis)agree?

**Comment by mikeboers** [comment] 2018-04-10 00:53
Oh damn. I've been doing the GIL wrong in PyAV this whole time. The `nogil` in the headers simply marks it as not needing the GIL, not that it will actually release it! I need to do it manually around everything.

**Comment by mikeboers** [comment] 2018-04-10 01:00
Please see [this branch](https://github.com/mikeboers/PyAV/tree/feature/threading) for working cross-container threaded decoding.

**Comment by mikeboers** [comment] 2018-04-10 01:10
Removing the eager open entirely only breaks a few tests that have to do with options and such. I believe we should go in that direction.

Also, a sensible default may be to set `thread_count` to `0` and `thread_type` to `3` (or whatever would catch both of them).

**Comment by wegel** [comment] 2018-04-10 01:32
Getting the same ultra nice performance boost with the `feature/threading` branch, nice work ;)

**Comment by wegel** [comment] 2018-04-10 01:34
What's odd is that I get the same behaviour wether I set `thread_count` and/or `thread_type`, so even when I do nothing special, I get the multiple threads and performance boost.

**Comment by mikeboers** [comment] 2018-04-10 01:36
Cool.

I think we're supposed to pick one of `FF_THREAD_SLICE` or `FF_THREAD_FRAME`, but not both. That should be looked into.

Perhaps a `Container.set_threads(count, type=???)` could be added to configure threads across all streams at once.

Re 2nd message: Depends on what the Python side is doing over here. If there is only one Python thread then the `thread_count` matters. And I think I defaulted to `0` which gets adjusted to the number of CPUs.

**Comment by mikeboers** [comment] 2018-04-10 01:41
Looking at [`ff_thread_init`](https://ffmpeg.org/doxygen/2.0/libavcodec_2pthread_8c_source.html#l01097) and [`validate_thread_parameters`](https://ffmpeg.org/doxygen/2.0/libavcodec_2pthread_8c_source.html#l01073) I'd say it is safe to set the `type` to `3`; it will try one and then the other.

**Comment by wegel** [comment] 2018-04-10 01:42
Agreed, that's pretty much what I gathered in my initial investigation earlier today.

**Comment by Kamekameha** [comment] 2018-04-10 01:56
> Oh damn. I've been doing the GIL wrong in PyAV this whole time. The nogil in the headers simply marks it as not needing the GIL, not that it will actually release it! I need to do it manually around everything.

To be honest when I read your comment about [the `nogil` markers](https://github.com/mikeboers/PyAV/issues/303#issuecomment-379860888) earlier I thought that while it was slightly misleading, you surely knew what these mean and that the GIL should be managed manually regardless, mostly because there are indeed frequent instances of the `with nogil:` context manager in the codebase. Maybe something you forgot over time?

<sub>(Yes I know, this isn't constructive at all. Just felt like commenting about it either way. :) )<sub/>

**Comment by mikeboers** [comment] 2018-04-10 11:49
I can see how my `nogil` comment could have been read snarky/arrogant, so subtle I-told-you-so accepted. 😁🍻 

I totally forgot how they worked. As you can no doubt tell, I had assumed that was a shortcut for signalling automatic GIL release when calling those functions, not just that they don't need the GIL.

(I don't actually spend a lot of time in Cython anymore.)

**Comment by mikeboers** [comment] 2018-04-10 18:29
@wegel I changed the default `thread_type` to 2 (slices), because it doesn't change the interaction with the API at all (and tests started failing when I moved this to the `CodecContext` from `Stream`). `thread_type` 1 (frames) will delay frames, or have other requirements from the client.

I'm open to arguments, however.

I also want to change `thread_type` to an enum or something, so you can set `stream.thread_type = 'frame'` `'slice'` or `'any'`.

**Comment by wegel** [comment] 2018-04-13 22:26
Regarding the enum, of course it would be better than the obfuscated bitwise int.

I tried the latest version of the 'feature/threading' branch, and with `thread_type = 2` (eg, by using the default) I'm not getting any performance improvement (while mainly encoding) over what I was getting before.

Therefore for now on my local build of PyAV I'll continue using `thread_type = 3`. I'll read up more on the requirements needed for ffmpeg's FF_THREAD_FRAME, though. Thanks!

**Comment by mikeboers** [comment] 2018-05-10 17:18
I rolled my own enums that nearly mimick the stdlib ones. I've now merged this into develop. I'll open a new issue to discuss changing the default.

**Closed by mikeboers** 2018-05-10 17:18 UTC
Labels: design, enhancement

**Comment by kli-nlpr** [comment] 2018-10-26 00:58
@wegel  Can you share your code? thanks

**Comment by fzqneo** [comment] 2019-11-07 20:15
when `thread_type='SLICE'`, setting `thread_count` doesn't seem to have any effect. It always uses one or two cores on my CPU. Is it expected?

**Comment by mfoglio** [comment] 2021-06-03 18:37
Hello, following up, how do ylou allow to

> My finding was same as @mikeboers, multiple containers will not decode at the same time. @wegel: I might have some time this month to dig deeper into this, if you need help.

Following up 3 years later, how can I have multiple containers decoding at the same time?

**Comment by fatalis** [comment] 2023-12-11 20:37
> To enable multiple threads within a single container, they must be set before [the codec is opened](https://github.com/mikeboers/PyAV/blob/develop/av/stream.pyx#L81), which means we get to make it so that you can either pass in stream attributes to `av.open`, or delay opening codecs.

I'm trying to set `thread_count` and struggling. `stream_options=['thread_count': '12'}]` in `av.open` is my best guess but it doesn't work. What am I missing? @mikeboers
