### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by cswhjiang** [mikeboers/PyAV#626] opened 2020-04-17 07:17 UTC
Here are the error messages:
````
Building wheels for collected packages: av
  Building wheel for av (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/setup.py'"'"'; __file__='"'"'/dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /dockerdata/wenhaojiang/tmpdir/pip-wheel-zbiltngd
       cwd: /dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/av
  copying av/__init__.py -> build/lib.linux-x86_64-3.6/av
  copying av/__main__.py -> build/lib.linux-x86_64-3.6/av
  copying av/datasets.py -> build/lib.linux-x86_64-3.6/av
  copying av/deprecation.py -> build/lib.linux-x86_64-3.6/av
  creating build/lib.linux-x86_64-3.6/av/audio
  copying av/audio/__init__.py -> build/lib.linux-x86_64-3.6/av/audio
  creating build/lib.linux-x86_64-3.6/av/codec
  copying av/codec/__init__.py -> build/lib.linux-x86_64-3.6/av/codec
  creating build/lib.linux-x86_64-3.6/av/container
  copying av/container/__init__.py -> build/lib.linux-x86_64-3.6/av/container
  creating build/lib.linux-x86_64-3.6/av/data
  copying av/data/__init__.py -> build/lib.linux-x86_64-3.6/av/data
  creating build/lib.linux-x86_64-3.6/av/filter
  copying av/filter/__init__.py -> build/lib.linux-x86_64-3.6/av/filter
  creating build/lib.linux-x86_64-3.6/av/sidedata
  copying av/sidedata/__init__.py -> build/lib.linux-x86_64-3.6/av/sidedata
  creating build/lib.linux-x86_64-3.6/av/subtitles
  copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.6/av/subtitles
  creating build/lib.linux-x86_64-3.6/av/video
  copying av/video/__init__.py -> build/lib.linux-x86_64-3.6/av/video
  running build_ext
  running config
  pkg-config returned flags we don't understand: -pthread
  ----------------------------------------
  ERROR: Failed building wheel for av
  Running setup.py clean for av
Failed to build av
Installing collected packages: av
    Running setup.py install for av ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/setup.py'"'"'; __file__='"'"'/dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /dockerdata/wenhaojiang/tmpdir/pip-record-11_bupre/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /dockerdata/wenhaojiang/.local/include/python3.6m/av
         cwd: /dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/av
    copying av/__init__.py -> build/lib.linux-x86_64-3.6/av
    copying av/__main__.py -> build/lib.linux-x86_64-3.6/av
    copying av/datasets.py -> build/lib.linux-x86_64-3.6/av
    copying av/deprecation.py -> build/lib.linux-x86_64-3.6/av
    creating build/lib.linux-x86_64-3.6/av/audio
    copying av/audio/__init__.py -> build/lib.linux-x86_64-3.6/av/audio
    creating build/lib.linux-x86_64-3.6/av/codec
    copying av/codec/__init__.py -> build/lib.linux-x86_64-3.6/av/codec
    creating build/lib.linux-x86_64-3.6/av/container
    copying av/container/__init__.py -> build/lib.linux-x86_64-3.6/av/container
    creating build/lib.linux-x86_64-3.6/av/data
    copying av/data/__init__.py -> build/lib.linux-x86_64-3.6/av/data
    creating build/lib.linux-x86_64-3.6/av/filter
    copying av/filter/__init__.py -> build/lib.linux-x86_64-3.6/av/filter
    creating build/lib.linux-x86_64-3.6/av/sidedata
    copying av/sidedata/__init__.py -> build/lib.linux-x86_64-3.6/av/sidedata
    creating build/lib.linux-x86_64-3.6/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.6/av/subtitles
    creating build/lib.linux-x86_64-3.6/av/video
    copying av/video/__init__.py -> build/lib.linux-x86_64-3.6/av/video
    running build_ext
    running config
    pkg-config returned flags we don't understand: -pthread
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/setup.py'"'"'; __file__='"'"'/dockerdata/wenhaojiang/tmpdir/pip-install-j_hc1pmb/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /dockerdata/wenhaojiang/tmpdir/pip-record-11_bupre/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /dockerdata/wenhaojiang/.local/include/python3.6m/av Check the logs for full command output.
````

ffmpeg output:
````
ffmpeg version N-97357-g8e30502 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (GCC)
  configuration: --pkg-config-flags=--static --extra-libs=-lpthread --extra-libs=-lm --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 79.100 / 58. 79.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.101 /  7. 77.101
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
````

**Comment by cswhjiang** [comment] 2020-04-17 08:10
Problem solved. I follow https://trac.ffmpeg.org/wiki/CompilationGuide/Centos to install ffmpeg. But for x264 and ffmpeg, I used the following configuration:
````
./configure  --enable-pthread --enable-mp4-output --enable-shared
````
````
./configure \
	--disable-doc \
	--disable-mmx \
	--disable-optimizations \
	--disable-static \
	--disable-stripping \
	--enable-debug=3 \
	--enable-gpl \
	--enable-libx264 \
	--enable-shared
````

After that, pip install succeeded.

**Comment by jlaine** [comment] 2020-04-22 07:47
Right this is a duplicate of #510

**Closed by jlaine** 2020-04-22 07:47 UTC
Labels: build
