### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by nicosmik** [mikeboers/PyAV#38] opened 2014-07-17 14:28 UTC
Hi,
I would like to use PyAV under Python2.7 on windows.
Can you explain me how I can install the plugin?
(I would like a more recent version than the 0.1.0)
Thank you.
Nico

**Comment by MichaelBarz** [comment] 2015-06-12 14:05
Hi. I recently followed the instructions to create PyAV-wheel for windows.
To do so I used https://github.com/rdp/ffmpeg-windows-build-helpers to cross-compile ffmpeg 32-bit with Ubuntu 14.04 LTS for Windows. Afterwards I followed the given steps until I ran into trouble with step no. 5 `make build-mingw32`. I received the following errors:
![cmd_err](https://cloud.githubusercontent.com/assets/6330614/8131743/abc1dd50-111c-11e5-99e9-399d16375cda.png)

Any idea?

Best,
Michael

**Comment by MichaelBarz** [comment] 2015-06-14 09:07
Hi,

unfortunately I still have problems with setting up PyAV for Windows. Here some system specs for clarification
* Windows 8 x64 in a VM
* Python27 32-bit
* TDM-GCC Toolchain for 32-bit (http://tdm-gcc.tdragon.net/)

Further I use my own build of ffmpeg that I cross-compiled with Ubuntu 14.04 LTS in my previous post.
The PKG_CONFIG_PATH is set to the corresponding folder of my ffmpeg build.

Running `make build-mingw32` starts building av\codec. However the process holds when generating the `codec.pyd` file with some undefined references:
![cmd_err](https://cloud.githubusercontent.com/assets/6330614/8147967/562565e6-1285-11e5-8471-ee4480307b5c.png)

Did someone already experience this issue? Maybe there is a missing dependency for the setup.py?

Best,
Michael

**Comment by MichaelBarz** [comment] 2015-07-09 16:07
I finally figured out how to build PyAV for Windows. The problem above was caused by my Python version. I had 2.7.10 installed, which was not compatible. Installing an older version (I chose 2.7.6) solved that problem.

**Comment by mikeboers** [comment] 2015-07-13 15:07
The Python version matters, huh? Interesting...

**Comment by vidartf** [comment] 2015-08-11 15:17
Trying to set up PyAV on windows here too. For me, the ideal solution would be a bdist-wheel on PyPI built against the [official windows shared ffmeg build](http://ffmpeg.zeranoe.com/builds/).

**Comment by MichaelBarz** [comment] 2015-08-11 20:55
like that: https://github.com/MichaelBarz/PyAV/tree/master/dist ;)

**Comment by vidartf** [comment] 2015-08-11 22:29
Sure (except I need the 64-bit one). I've modified setup.py to be able to build on windows without ffmpeg source, and using either MSVC python compiler or MinGW. I'll clean it up and PR tomorrow.

**Comment by jlarsch** [comment] 2016-03-07 10:18
Hi,
I would love to use pyAV on my windows 64bit, 2.7.11 |Anaconda 2.3.0 (64-bit) configuration.
I have tried to follow the instructions [here](http://mikeboers.github.io/PyAV/installation.html) and [here](http://www.helyar.net/2014/compile-ffmpeg-64-bit-on-windows-with-msysmingw-w64/). I compiled ffmpeg but I can't make sense out of the sparse instructions for pyAV installation.
Can anyone provide a step by step command list that works on a windows machine or perhaps a wheel file?

**Comment by monicabm** [comment] 2016-06-15 21:50
I was wondering if you were able to find the step by step command list or a wheel file for a windows 64bit version...

**Comment by eliziario** [comment] 2017-08-25 18:43
hey @vidartf did you manage to create this that PR? still have this diff around?

**Comment by vidartf** [comment] 2017-08-25 19:08
Hey. My original PRs are here: https://github.com/mikeboers/PyAV/pulls?q=is%3Apr+author%3Avidartf+is%3Aclosed  . Some of these are marked as closed instead of merged, because the repo owner rewrote them partly (so not sure if any commits in repo are in my name). I have no memory of this as it is quite a long while ago. Also, I think this was originally merged, so if it is again not working you might have to do something else.

**Comment by mikeboers** [comment] 2017-08-27 12:52
@vidartf I do end end up rewriting history a bit with PRs, but I try very hard to retain original authorship information (often I'll be the "committer" and the author is the author; I'm getting better at it. 😛).

I'm pretty sure everything found in that link was incorporated in some form or another.

**Closed** 2018-10-09 12:37 UTC
Labels: build
