### ISSUE TITLE
File descriptors are not closed for `InputContainer`

### ISSUE THREAD

**Issue by pavloivanchyshyn** [mikeboers/PyAV#286] opened 2018-02-20 15:33 UTC
When we try to open files using:

```
import av
streams = av.open('file.ts').streams
```
It doesn't close file descriptor for `file.ts`. This might raise an `Too many open files:` error.

P.S. OutputContainer works fine in this situation.

**Comment by willfrey** [comment] 2018-03-12 18:49
This is also an issue for me!

**Comment by jlaine** [comment] 2018-11-07 13:01
File descriptors should actually be closed by the destructor, can you confirm that the issue is still present in PyAV 6.0.0?

It would be nice to have an explicit `close` method though.

**Comment by mikeboers** [comment] 2018-11-07 14:54
We did fix up the destructors, but I agree a `close` would be nice.

Closing this to make another one.

**Closed by mikeboers** 2018-11-07 14:54 UTC
