### ISSUE TITLE
Cannot install PyAV

### ISSUE THREAD

**Issue by aspen1135** [mikeboers/PyAV#531] opened 2019-06-03 00:12 UTC
The Problem:

For some reason, no matter what guide I follow or what I install, I keep getting this error while trying to build the PyAV module using either developer command prompt for VS 2019 or just a basic command shell:

```
building 'av.buffer' extension

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/ 
```

Build Tools:

Build tools for VS 2019 is already installed on my system, as well as C++ 2015-2019 redistributable (x64) 14.21.27702. I am using Python 3.7 which, according to the documentation online, should only need versions 2017 or higher. While troubleshooting this issue, I found another python compiler guide claiming I'd need the windows SDK. It provides a dead link for the windows 7 SDK tools, but I still managed to find the windows 10 SDK from the microsoft webpage. However, installing it made no difference to the issue.

According to the PyAV's website, this module is also available through the conda-forge repository and includes all the dependencies with it. While trying that approach, it builds the module correctly but it not let me run any code from the av library after importing it into python script. It detects the classes and functions, but anytime you launch any code it says it is missing DLL modules. More specifically, the error is:

```
C:\ProgramData\Anaconda3\python.exe "C:/Users/Admin/Google Drive/1. Software Engineering/Python/Samplify/asdfasef.py"
Traceback (most recent call last):
  File "C:/Users/Admin/Google Drive/1. Software Engineering/Python/Samplify/asdfasef.py", line 1, in <module>
    import av
  File "C:\ProgramData\Anaconda3\lib\site-packages\av\__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: DLL load failed: The specified module could not be found.
```

This is after running the 'basics' code on the PyAV website: 

```
import av
import os


path_to_video = 'C:\\Users\\Admin\\Downloads\\video.mp4'

container = av.open(path_to_video)

os.chdir('C:\\Users\\Admin\\Downloads\\')  #chdir in case file outputted somewhere else

for frame in container.decode(video=0):
    frame.to_image().save('frame-%04d.jpg' % frame.index)

```

I have the latest stable version of FFmpeg shared installed (the distro with the DLL files in the /bin), and it has been added to my path as `C:\ffmpeg4.1.3shared`. Additionally, I have searched for specific .DLL dependencies within the Anaconda installation directory and they do exist. It is my guess that despite it building the module correctly and downloading all the dependencies, it still cannot link to them for some reason.

The only thing I can think of, is to start from square one and build PyAV manually, since upon building the module, you can also include an argument to point to the specific FFmpeg installation path.

Of course, I need the C/C++ build environment to get this working and as I stated before, I cannot, despite having installed everything that is recommended by other posts.

I still have not figured out how to get this working. I am at a complete loss of what to do, and my project has taken a complete halt because of it. I have spent over a week installing packages, adding things to path and trying to get things to work. Please help!

![image](https://user-images.githubusercontent.com/17952043/58769172-405e0d80-8559-11e9-83da-ccef9d96869d.png)

![image](https://user-images.githubusercontent.com/17952043/58769177-566bce00-8559-11e9-8c2b-2e10ff2c55fb.png)

![image](https://user-images.githubusercontent.com/17952043/58769195-74393300-8559-11e9-9bb5-518670425474.png)

**Comment by jlaine** [comment] 2019-06-03 10:11
This looks like a duplicate of #466

**Comment by aspen1135** [comment] 2019-06-03 12:26
Ah. Okay well before you close this post, let me make sure that installing visual studio 2015 fixes it.

I don't know why the official python docs haven't been updating or are providing wrong information. Python website says Python 3.5 or above uses 2017 or higher.

**Comment by aspen1135** [comment] 2019-06-03 13:07
I uninstalled the newer versions of visual studio 2017-2019, including build tools.

Then, installed visual studio 2015 & build tools 2015 sourced [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145) & [here](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159).

And I still have this issue. 
![image](https://user-images.githubusercontent.com/17952043/58804057-c7e16600-85c5-11e9-9cf4-fbc1022b04e7.png)

![image](https://user-images.githubusercontent.com/17952043/58804087-d7f94580-85c5-11e9-85db-b9a645b8307d.png)

**Comment by aspen1135** [comment] 2019-06-03 13:14
> There a several problems in this issue. The first part looks like a duplicate of #466, the second part like a duplicate of #467

The first reference #466, does not have the same error. Also, following the same steps does not fix the issue. The second part #467, again, is a slightly separate error and the post does not have a solution.

I'm not sure what to do here still.

**Comment by aspen1135** [comment] 2019-06-03 14:49
UPDATE:

It seems as though you can no longer download the visual studio 2015 suite from the microsoft website. When I tried downloading one through a mirror, even though the installer strictly said "Visual Studio 2015 community edition", it automatically updated it to 2017.

However, after downloading and installing the C++ packages and the python development tools, I was able to get passed the 'missing microsoft visual studio' error.

Now, I am having the same problem that #466 and #467 are having, where I get:

```
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
```

**Comment by All4Gis** [comment] 2019-06-13 16:58
I'm having the same error in Windows 10.
I have PATH pointing to the `D:\ffmpeg\bin` folder.
Any solution on this?
```
from av._core import time_base, pyav_version as __version__
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by aspen1135** [comment] 2019-06-13 20:16
> I'm having the same error in Windows 10.
> 
> ```
> from av._core import time_base, pyav_version as __version__
> ImportError: DLL load failed: The specified module could not be found.
> ```
> 
> Finally solve it by copying the dll in the library folder.
> 
> * avcodec-58.dll
> * avdevice-58.dll
> * avfilter-7.dll
> * avformat-58.dll
> * avutil-56.dll
> * postproc-55.dll
> * swresample-3.dll
> * swscale-5.dll

This is a bit of a separate issue than OP. that has to do with finding the DLL files, where this op has to do with building the module from source.

I did run into this same issue you are describing, but when installing through anocanda. My solution was to add the specific ffmpeg distro that came with the anocanda packages to PATH because it didn't do it automatically. Using another distro outside of the one that is included in the install will result in it throwing the exception as well. The ffmpeg build has to be specific to the one used when building the PyAV module I believe.

**Comment by egao1980** [comment] 2019-07-24 09:42
This requires `python setup.py build_ext --inplace` for development. Please read doc section on building from source.

If you just need to use a specific PyAV branch you can use `pip install git+https://github.com/egao1980/PyAV.git@audio-filters#egg=av` command to install it, in this example I'm installing my fork's branch.

**Comment by aspen1135** [comment] 2019-07-26 02:36
Just a bit of an update: I wanted to bring the comments back to this thread where it probably more appropriately belongs.

> > This might require more work, as AppVeyor x64 build in conda 3.7 also fails. Try either 3.6 or 32 bit Python / FFMpeg.

Tried working on this more today. Ran into some more problems.

I downloaded and installed python 3.6 to a seperate location. I made sure to clear my PATH variables and ensure the running python was on 3.6. These following problems occur on both 64 bit and 32 bit versions of Python (I've tried both).

The first thing I ran into, was it was still not detecting the C++ compiler in the path and throwing a cl.exe error 'no file found'. So I added `'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\` to PATH and fixed that error.

Next I ran into `io.h not found`, and added `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt;` to PATH. Interestingly enough, this error would still be thrown regardless of it being added to PATH. I could even open the `io.h` script directly by typing "io.h" into the cmd shell, confirming that it's being recognized in PATH.

So next thing I tried was just to copy/paste all the `.h` scripts into the `Python 3.6\include` folder. This got me past the `io.h` error.

Now it's wanting another missing script from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include` so I add that to PATH and the same behavior occurs, same as `io.h`, the installer doesn't like the file being added to global PATH environment. So instead, I follow the previous trick and copy the `.h` scripts from that location to `Python 3.6\include` and get passed this error once again.

But then another missing `.h` script error occurs...

**** me. How many times do I have to do this?

There _has_ to be an easier way to do this and get the environment working. Why can't python find any of my visual studio resources, even after being added to PATH?

This is what all of my system PATH variables look like right now: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Python 3.6;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include;`

Just to re-iterate: This occurs on both 32 bit and 64 bit versions of Python. I am in windows 7 Ultimate x64 bit. I also have a laptop running Windows 10 x64 bit and have tried similar steps and ran into the same issues.

**Comment by dustsigns** [comment] 2019-12-07 06:01
The Visual Studio compiler (and linker) not being able to find the headers is because it does not use the `PATH` variable. This is in the official compiler documentation, but still rather counter-intuitive.  I described how to set the compiler and linker variables for PyAV step by step in [this gist](https://gist.github.com/dustsigns/978f505cd190b7e64f140d6295faf62a). I hope it helps.

**Comment by RoscoeTheDog** [comment] 2020-03-01 07:05
> The Visual Studio compiler not being able to find the headers is because it does not use the `PATH` environment variable. This is in the official compiler documentation, but still rather counter-intuitive. I described how to set the compiler and linker variables for PyAV step by step in [this gist](https://gist.github.com/dustsigns/978f505cd190b7e64f140d6295faf62a). I hope it helps.

Sorry I have not been as active on updating these created issues, since my own little project's development has taken a halt as life and school has picked up. @dustsigns your documentation was exactly what I needed in order to get it to build and work correctly. Thank you for supplying that.

I am hoping that the owners of this Repo will adopt your document to their own documentation. It's much more thorough than anything on the Wiki or main website. I have saved it for my own future reference.

**Comment by jlaine** [comment] 2020-04-26 12:00
As of PyAV 8.0.0, binary wheels are provided which will greatly simplify installation and should solve your issue.

**Closed by jlaine** 2020-04-26 12:00 UTC
Labels: duplicate
