### ISSUE TITLE
av.open() blocking for a long time on highly compressed webm audio

### ISSUE THREAD

**Issue by davidavdav** [mikeboers/PyAV#445] opened 2018-10-24 13:44 UTC
Hi, 

We use pyav for decoding web audio codecs.  Recently we've tried to lower the bitrate on the web-encoding side, and found that this results in `av.open(named_pipe)` to block for a longer period, something like 2 seconds worth of audio frames or so.  (We write the audio to the `named_pipe` as it comes in from the web client in chunks of about 0.25 s.)

My suspicion is that it takes `libab.avformat-open_input()` a certain number of input bytes before it has finally decided on the format, and with these low bit rates, that simply takes many frames (of size ~ 250 B) to reach this number.  With lower compression, `av.open()` returns after the first frame (of size ~ 2kB) and we effectively get a lower latency with smaller compression. 

I've tried several AVFormatContext options in the `options=` argument of `av.open()`, `probesize`, `max_delay`, `analyzeduration`, but none seem to make any difference.  

Does anyone know a way around this?

**Comment by jlaine** [comment] 2018-11-05 14:43
Another candidate for the blocking operation is `avformat_find_stream_info`. Note that since both `avformat_open_input` and `avformat_find_stream_info` are called with the GIL released, only the current thread should be "blocked".

**Comment by mikeboers** [comment] 2018-11-06 17:44
With the data from #448, i tried removing `avformat_find_stream_info` and that isn't the problem.

So... coming to this topic from the other one... try setting `format='webm'` in your `av.open`.

**Comment by jlaine** [comment] 2018-11-06 17:51
OK, let's close this, the probing is definitely the root cause.

**Closed by jlaine** 2018-11-06 17:51 UTC

**Comment by davidavdav** [comment] 2018-11-06 20:11
OK, thanks, setting the format seems to be the solution for the long latency.   

Strange that ffmpeg has a minimum for the probe size specified in bytes---for hight compression this is killing the latency.
